### PR TITLE
Update ngHandsontable to use current version of Handsontable

### PR DESCRIPTION
**Pull request by michalsnik**
I updated ngHandsontable to use current version of Handsontable and fixed an issue with "PluginHooks not defined" after update.

### CODE REVIEW

**Comment by michalsnik** [comment]
I updated pull request, because it turned out Handsontable has slightly different API in new version than i expected. And there is no need to get Object.keys if new API has method that returns keys by default.

**Comment by victorsosa** [comment]
1+

**Comment by sarahquigley** [comment]
+1

**Comment by darkmavis1980** [comment]
+1

**Pull request merged**
